FROM node:16-alpine

# Define build arguments
ARG SENTRY_DSN
ARG APP_VERSION
ARG DATABASE_NAME
ARG ENVIRONMENT
ARG MONGODB_URL
ARG PORT
ARG ISSUER
ARG AWS_ACCESS_KEY_ID_EMAIL
ARG AWS_SECRET_ACCESS_KEY_EMAIL
ARG AWS_ACCESS_KEY_ID_KYC
ARG AWS_SECRET_ACCESS_KEY_KYC
ARG AWS_REGION
ARG AWS_SES_PROFILE_NAME
ARG SECRET_KEY

# Set environment variables
# It is intentional why all the variables are set as secrets
ENV SENTRY_DSN=$SENTRY_DSN
ENV APP_VERSION=$APP_VERSION
ENV DATABASE_NAME=$DATABASE_NAME
ENV ENVIRONMENT=$ENVIRONMENT
ENV MONGODB_URL=$MONGODB_URL
ENV PORT=$PORT
ENV ISSUER=$ISSUER
ENV AWS_ACCESS_KEY_ID_EMAIL=$AWS_ACCESS_KEY_ID_EMAIL
ENV AWS_SECRET_ACCESS_KEY_EMAIL=$AWS_SECRET_ACCESS_KEY_EMAIL
ENV AWS_ACCESS_KEY_ID_KYC=$AWS_ACCESS_KEY_ID_KYC
ENV AWS_SECRET_ACCESS_KEY_KYC=$AWS_SECRET_ACCESS_KEY_KYC
ENV AWS_REGION=$AWS_REGION
ENV AWS_SES_PROFILE_NAME=$AWS_SES_PROFILE_NAME
ENV SECRET_KEY=$SECRET_KEY


WORKDIR /usr/src/app

COPY package*.json ./

RUN npx yarn install

COPY . .

RUN npx yarn build

EXPOSE 3000

CMD ["node", "dist/index.js"]
